import os
import shutil
import tempfile
import traceback
import logging
from fastapi import FastAPI, File, UploadFile
from fastapi.responses import JSONResponse
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pipeline import run_pipeline
from dashboard_generator import generate_dynamic_dashboard

# Configure logging to see errors
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)

app = FastAPI(
    title="FYRP Adversarial Threat Detection API",
    description="Backend API for Explanable Multi-Agent AI-Based Adversarial Threat Detection",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

os.makedirs("results", exist_ok=True)
app.mount("/results", StaticFiles(directory="results"), name="results")

CHECKPOINT_PATH = "checkpoints/best_model.pth"

@app.post("/analyze")
async def analyze_image(file: UploadFile = File(...)):
    """
    Endpoint to analyze a facial biometric image for adversarial threats.
    """
    temp_dir = tempfile.mkdtemp()
    temp_file_path = os.path.join(temp_dir, file.filename)
    
    try:
        # Save the uploaded file temporarily
        with open(temp_file_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)
            
        # Determine if checkpoint exists
        checkpoint_to_use = CHECKPOINT_PATH if os.path.exists(CHECKPOINT_PATH) else None
        
        # Run the end-to-end pipeline
        result = run_pipeline(
            image_path=temp_file_path,
            checkpoint=checkpoint_to_use,
            verbose=False
        )
        
        if result.get("heatmap_path"):
            # Generate the unified XAI dashboard
            heatmap_filename = os.path.basename(result["heatmap_path"])
            stem = os.path.splitext(heatmap_filename)[0].replace("_gradcam", "")
            dashboard_filename = f"{stem}_dashboard.png"
            dashboard_path = os.path.join("results", dashboard_filename)
            
            pure_overlay_path = result["heatmap_path"].replace("_gradcam.png", "_pure_overlay.png")
            
            generate_dynamic_dashboard(
                image_path=temp_file_path,
                gradcam_path=pure_overlay_path,
                report=result,
                output_path=dashboard_path
            )
            
            # Send only the dashboard URL to the UI
            result["dashboard_url"] = f"http://localhost:8001/results/{dashboard_filename}"
            
            # Remove intermediate visualization files from the results directory
            try:
                if os.path.exists(result["heatmap_path"]):
                    os.remove(result["heatmap_path"])
                if os.path.exists(pure_overlay_path):
                    os.remove(pure_overlay_path)
            except Exception as e:
                print(f"Warning: Could not remove intermediate visuals: {e}")
                
            # Optional: remove the heatmap_path from the API response so the UI doesn't try to load it
            if "heatmap_path" in result:
                del result["heatmap_path"]
        
        # Return the report generated by the pipeline
        return JSONResponse(content=result)
        
    except Exception as e:
        error_msg = str(e)
        error_trace = traceback.format_exc()
        logger.error(f"Pipeline error: {error_msg}\n{error_trace}")
        print(f"ERROR in /analyze endpoint:\n{error_trace}")
        return JSONResponse(content={"error": error_msg, "traceback": error_trace}, status_code=500)
        
    finally:
        # Clean up the temporary file and directory
        try:
            if os.path.exists(temp_file_path):
                os.remove(temp_file_path)
            if os.path.exists(temp_dir):
                os.rmdir(temp_dir)
        except Exception as cleanup_error:
            logger.warning(f"Failed to clean up temporary files: {cleanup_error}")

@app.get("/health")
def health_check():
    """
    Health check endpoint.
    """
    return {"status": "healthy", "checkpoint_found": os.path.exists(CHECKPOINT_PATH)}

if __name__ == "__main__":
    import uvicorn
    # To run the server directly: python app.py
    uvicorn.run("app:app", host="0.0.0.0", port=8001, reload=False)
